// Sitemap only. robots.txt is generated by the App Router route at
// `src/app/robots.ts` — do not re-add next-sitemap's `generateRobotsTxt`. It would
// write a static `public/robots.txt`, which takes precedence over the route and would
// silently replace the working robots.txt with a version that has no sitemap pointer.
module.exports = {
	siteUrl: 'https://jorytindall.com',
};
