export default {
	name: `moduleContent`,
	title: `Module Content`,
	type: `array`,
	of: [
		{ type: `hero` },
		{ type: `mainImage` },
		{ type: `gallery` },
		{ type: `fullWidthImage` },
		{ type: `richText` },
		{ type: `form` },
		{ type: `brandLogoBlock` },
		{ type: `impactBlock` },
		{ type: `portfolioList` },
		{ type: `results` },
		{ type: `features` },
		{ type: `tabs` },
		{ type: `stravaStats` },
	],
};
