name: CI - web

on:
    push:
        branches:
            - main
    pull_request: {}

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Install dependencies
              run: pnpm install

            - name: Build application
              run: cd apps/web && pnpm build
              env:
                  NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
                  NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
                  SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}

            - name: Install Playwright and browsers
              working-directory: apps/web
              run: |
                  pnpm install @playwright/test
                  pnpm exec playwright install --with-deps

            - name: Run Playwright tests
              working-directory: apps/web
              run: pnpm exec playwright test
              env:
                  CI: true
                  PLAYWRIGHT_JSON_OUTPUT_NAME: test-results.json
                  NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
                  NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
                  SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}

            - uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: playwright-report
                  path: apps/web/playwright-report/
                  retention-days: 30
